### PR TITLE
Pushing to Ryan

### PR DESCRIPTION
**Pull request by tisaconundrum2**
set of changes.
Things to note:

- Plot has been changed on Nick's end, and should be verified for runnability 
- Restoring currently only works for certain modules.
- Some modules still have deprecated code that needs to be fixed.
- Lack of restoring will not hold back ability to run a workflow normally.

**Completed restoration on modules:**
- [x] file_outpath_.py
- [x] get_mask_.py
- [x] get_data_.py
- [x] interpolation_.py
- [x] strat_folds_.py
- [ ] cv_.py
- [ ] plot_.py
- [ ] regression_predict_.py
- [ ] regression_train_.py
- [ ] removenull_.py
- [ ] sm_.py
- [ ] write_data_.py

**Currently working on:**
- [ ] normalization_.py

### CODE REVIEW

**Comment by tisaconundrum2** [comment]
New pull request, see if that fixes the problem

**Comment by ryanbanderson** [comment]
Ok, that fixes deleting normalization, but it doesn't fix the issue with
deleting mask but the program still trying to run the deleted module.

Here's the console message:
C:\Users\rbanderson\AppData\Local\Continuum\Anaconda3\python.exe
"C:/Users/rbanderson/Documents/Projects/LIBS PDART/PySAT/src/Python
PYSAT_GUI/pysat_main.py"
C:\Users\rbanderson\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\fixes.py:64:
DeprecationWarning: inspect.getargspec() is deprecated, use
inspect.signature() instead
  if 'order' in inspect.getargspec(np.copy)[0]:
[0, 'get_known_data', 'get_data',
['C:/Users/rbanderson/Documents/Projects/LIBS
PDART/Sample_Data/full_db_mars_corrected_dopedTiO2_pandas_format.csv',
'known'], {}]
Loading data file: C:/Users/rbanderson/Documents/Projects/LIBS
PDART/Sample_Data/full_db_mars_corrected_dopedTiO2_pandas_format.csv
[1, None, None, None, None]
getattr(): attribute name must be string
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread

And a screenshot of what the UI looks like:
[image: Inline image 1]


Ryan Anderson
Physical Scientist / Developer
USGS Astrogeology Science Center
2255 N. Gemini Dr.
Flagstaff, AZ 86001
Cell: 734-657-8085
Office: 928-556-7239
rbanderson@usgs.gov

**Comment by ryanbanderson** [comment]
Nevermind, please ignore me. I messed with the deletion code thinking I was
fixing a different issue, and that caused this issue!


Ryan Anderson
Physical Scientist / Developer
USGS Astrogeology Science Center
2255 N. Gemini Dr.
Flagstaff, AZ 86001
Cell: 734-657-8085
Office: 928-556-7239
rbanderson@usgs.gov

**Comment by tisaconundrum2** [comment]
Is it all working alright for you now?

[image: Inline image 2]

Nicholas Finch
Northern Arizona University
President - NAU Robotics
BS Computer Science

**Comment by ryanbanderson** [comment]
Yes, I think so. I will let you know if (when?) I break something else...

**Comment by tisaconundrum2** [comment]
LOl alright

[image: Inline image 2]

Nicholas Finch
Northern Arizona University
President - NAU Robotics
BS Computer Science

**Pull request merged**
